# http://www.appveyor.com/docs/appveyor-yml

# configuration for develop/CI branch
-
  branches:
    only:
      - develop

  version: 2.1.3-dev
  configuration: Release
  pull_requests:
    do_not_increment_build_number: true
  
  init:
    - ps: Update-AppveyorBuild -Version "$($env:appveyor_build_version)$($env:appveyor_build_number.PadLeft(3, '0'))"
  
  # Install scripts. (runs after repo cloning)
  install:
    - nuget restore
  
  build:
    verbosity: minimal
  
  after_build:
    - cmd: Tools\GitLink.exe . -u https://github.com/ControlzEx/ControlzEx
    - cmd: nuget pack ControlzEx.nuspec -Version %appveyor_build_version% -Properties Configuration=%configuration%
    - ps: Get-ChildItem .\*.nupkg | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
  
  assembly_info:
    patch: true
    file: src\GlobalAssemblyInfo.*
    assembly_version: "{version}"
    assembly_file_version: "{version}"
    assembly_informational_version: "{version}"
  
  artifacts:
    - path: src/bin
      name: ControlzEx.$(appveyor_build_version)
      type: zip

# configuration for master/Release branch
-
  branches:
    only:
      - master

  version: 2.1.3.{build}
  configuration: Release
  pull_requests:
    do_not_increment_build_number: true
  
  # Install scripts. (runs after repo cloning)
  install:
    - nuget restore
  
  build:
    verbosity: minimal
  
  after_build:
    - cmd: Tools\GitLink.exe . -u https://github.com/ControlzEx/ControlzEx
    - cmd: nuget pack ControlzEx.nuspec -Version %appveyor_build_version% -Properties Configuration=%configuration%
    - ps: Get-ChildItem .\*.nupkg | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
  
  assembly_info:
    patch: true
    file: src\GlobalAssemblyInfo.*
    assembly_version: "{version}"
    assembly_file_version: "{version}"
    assembly_informational_version: "{version}"
  
  artifacts:
    - path: src/bin
      name: ControlzEx.$(appveyor_build_version)
      type: zip
